### ISSUE TITLE
Comparison with similar libraries

### ISSUE THREAD

**Issue by nevf** [jed/browserver-client#1]
Hi Jed, I haven't tried browserserver _(I'm away on a break)_ but I'm curious to know how it compares with libraries like Now.js, DNode, Socketstream etc. I am using Now.js in an app to update Browsers running Now.js connected to a Node.js server running Now.js

Neville

**Comment by jed** [comment]
neville,

this probably deserves its own FAQ, but for now, here are the main three differences as i see them:
- **browserver maintains very little state.** it only keeps references to open sockets both incoming and outgoing, shuttling data to and from browsers and servers. it doesn't attempt to synchronize anything, opting instead to push the burden of such logic to the edges.
- **browserver focuses on client-to-client communication.** the server component is only a proxy to connect long-lived servers on the Internet to short-lived servers in the browser.
- **browserver does not introduce any new APIs or formats.** it uses the node.js HTTP API on the client and the EventEmitter API on the server, using HTTP as the protocol that glues everything together. the server proxy doesn't even need to be JavaScript, and could just as easily be implemented in another language.
